spring:
  application:
    name: chat-forestfull
  profiles:
    default: dev
logging:
  level:
    root: INFO
jasypt:
  encryptor:
    password: ${key}
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.forestfull.member
  configuration:
    map-underscore-to-camel-case: true

---

# ==========================================
# DEV
# ==========================================
spring:
  config:
    activate:
      on-profile: dev


---
# ==========================================
# PROD
# ==========================================
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(UFLJPC0ERXwtinOfeCjhNvTdLmRdxYF1LM2JXB0ycgTc92QoQv7jUcvXyuQ62+R9cidxgSlPlFP78+MA+7dsLA==)
    username: ENC(gsxvIt9nz90E71Gruu/t/vB0aN/OSoR1yUCVwoKwzUu6SLygOdiPuZPzkVCQI4K5)
    password: ENC(rVp7g+kSrfAeLKCZUoNBprmGmR2gwPgZomFYKcgITl22DkPvStaP6R6fLQI25G1J)
logging:
  level:
    com.forestfull.chat: INFO
    org.apache.ibatis: WARN
tiktok:
  client-key: ENC(qrlI0ooMHLhyS/qLxNy2LupkXuFh4w9PHTVV8vG5mcTla9ZnzzH0F85jDPD4tvARSMy3zMldy66cvutm06EZ6g==)
  client-secret: ENC(3nyUHa/W+SXQP1KB/jGy7+AG2/0uyDpvG59vOJXQtdksOZdddF0ettrFxRhcbhZyvVR06RiI49WrAxiLJ9m2kwqfE/bUezdwxAtBUddcZ3A=)
  redirect-uri: ENC(YxQdJv9ifWD7obM1Vg09wFa9MfVtGU0XxuwNmGr2MEE3mUd2B+ZSeM6vmAA8j2yz5UXKWspazBZrji5AU58FJTfo6uxZGy00D8qy4opXz0NhwEtLQ+PNtOraVd1r5tkf)
  scope: ENC(JzLkw8d9LIl88ftdnPIwP6lI2v2x7U51WYT92t2dqmM4ciXL9tgH+SIiCFdwXJQq)