spring:
  application:
    name: chat-forestfull
  profiles:
    default: dev
logging:
  level:
    root: INFO
jasypt:
  encryptor:
    password: ${key}
mybatis:
  mapper-locations: classpath:mapper/**/*.xml

---

# ==========================================
# DEV
# ==========================================
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(yG1Tqfee4n7K6kKe5P2fcKNnppvrCGUCgVw0Sd8R9IGmIix02R0iHNgu9rqb8QQmTZQ+4Tfz6AFOPvl3k3YTIRE10VvXWAW0VBVorJ898lE2dI6E9lKHiRDgyqT9boedE9rzrPlSzy2qVCVNT0xuVrUHJ8tNHhgrTEH/zxBpu70=)
    username: ENC(T30E6AsfK5xzfaYkCm3y8Wv/LoaGtCDDMnyF2iJ82uTvXBiXrIeDnxXlHFXD9Fij)
    password: ENC(/QGU/qVE/mgOAn6eUUa0tnEByjxxmR/3VOmFn8nK6bFZ8Qj2wWxyZ1U2IKHnfvIT)
logging:
  level:
    com.forestfull.chat: DEBUG
    org.apache.ibatis: INFO
tiktok:
  client-key: ENC(j4Vs0fY54EW8BoO7YcGnTvOVIBY9IepImn5GE4zbfrr/U1vQr7RaoEo514M3CxOMmBcgf9uERhOqPeLtsBsF5A==)
  client-secret: ENC(2ppMrCEwzJkDDSQ//vZFDHz/nSct1HsE2MalcXAOcp3P7aMq81tbsj9a8bN4jBh1JQaz0rQ7Y7TIC7W64PiPqlG/BQWXX9uB+SO9cEfDzDM=)
  redirect-uri: ENC(w1+L6PxjcJ2GOZ10MNGpK4rh5AXIirfXdoQjpc+jzA+9Ufln2vipW4+PcPR5tlFoXqDrW4dAmgCoc0z0sfIbXSLSzT8qmQht8b3mmOOWLuA=)
  scope: ENC(zKFHbHeSfgRY/QrZazIbNo4EQrfYPv98cfrjWiAaDKfxDWlb5ClrlPjMnZ9mjqWV)

---
# ==========================================
# PROD
# ==========================================
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(VkWl/YF55J4zXYZLaaJlUcUXrDrv5b2U+/ss9Vpy3mX6R7DZ1MVxx1enarQDVwLudYIkIEH3/8grOJ77WB3f65n3TCeGdP7aiopR1MKxf9n3HkmXhDW53aTfWVwRAIX9lHIxyYDeoxvoPqTYom5nTg==)
    username: ENC(gsxvIt9nz90E71Gruu/t/vB0aN/OSoR1yUCVwoKwzUu6SLygOdiPuZPzkVCQI4K5)
    password: ENC(rVp7g+kSrfAeLKCZUoNBprmGmR2gwPgZomFYKcgITl22DkPvStaP6R6fLQI25G1J)
logging:
  level:
    com.forestfull.chat: INFO
    org.apache.ibatis: WARN
tiktok:
  client-key: ENC(qrlI0ooMHLhyS/qLxNy2LupkXuFh4w9PHTVV8vG5mcTla9ZnzzH0F85jDPD4tvARSMy3zMldy66cvutm06EZ6g==)
  client-secret: ENC(3nyUHa/W+SXQP1KB/jGy7+AG2/0uyDpvG59vOJXQtdksOZdddF0ettrFxRhcbhZyvVR06RiI49WrAxiLJ9m2kwqfE/bUezdwxAtBUddcZ3A=)
  redirect-uri: ENC(YxQdJv9ifWD7obM1Vg09wFa9MfVtGU0XxuwNmGr2MEE3mUd2B+ZSeM6vmAA8j2yz5UXKWspazBZrji5AU58FJTfo6uxZGy00D8qy4opXz0NhwEtLQ+PNtOraVd1r5tkf)
  scope: ENC(JzLkw8d9LIl88ftdnPIwP6lI2v2x7U51WYT92t2dqmM4ciXL9tgH+SIiCFdwXJQq)

