spring:
  application:
    name: chat-forestfull
  profiles:
    default: dev
logging:
  level:
    root: INFO
jasypt:
  encryptor:
    password: ${key}
    bean: jasyptStringEncryptor
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.forestfull
  configuration:
    map-underscore-to-camel-case: true

---

# ==========================================
# DEV
# ==========================================
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(D7FksKNaRiTUa4BwcImsF6HEHDJkt56FPqERYtMSsPP/eE+IO13MmNkERJEa+ctJ)
    username: ENC(j+pbKxXJNJx1XP3/lYjPiw==)
    password: ENC(S4n1c2JlysEjgHtwhkb1ZRneRh/IGFuK)
logging:
  level:
    com.forestfull.chat: DEBUG
    org.apache.ibatis: INFO
tiktok:
  client-key: ENC(ttOlI31RZl027PBkYcqbeDKZyfB6gpv/u7wCJ72Q5AI=)
  client-secret: ENC(7k8/DfgRorImyUPfE/9/1Rn4q8cnv7SOjm9AR/Ln1NCW7RvhhZTtyQxxS4j+cQ0i)
  redirect-uri: ENC(q2hrTSQpW0hod3Beq7KrDdkkO0jTt1lZLPXxAkG82B4cTsFiNC0DeKYZ3le2/Nl6)
  scope: ENC(RkFhNItvhRZgBIQYg2+65RWzDJAXFuFy)
file:
  directory:
    absolute: "C:/Development/test-storage/"


---
# ==========================================
# PROD
# ==========================================
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(YvqJNMByP56n98AhiegK57MxQFP8RfIx1U9fOujlhE0yFopiS0RLfw==)
    username: ENC(ZBZDdAwf0sT/raKt8MfxIw==)
    password: ENC(fhLYXOLuuJKsDhf5TRIfks71Y+AfHgSK)
logging:
  level:
    com.forestfull.chat: INFO
    org.apache.ibatis: WARN
tiktok:
  client-key: ENC(WiVfQrnIvUljbrkCVLu+Kv+z8NQPN1f5QcvInHIhBKg=)
  client-secret: ENC(uYKLrBXih3wkmb+7FhLk0sv9P+QMQjbL4YyIqgb4SgCk61XVoSY2Vd401uf68YhK)
  redirect-uri: ENC(ZEljp+4CHPI8Jp0IVKqppnqiPKFZ1m7p2LGOlweH7CZUwlCWKx5mpIRTU+RV4vIz)
  scope: ENC(sK07a57NUiOyrUqKitiDcHRU+CbjdOEv)
file:
  directory:
    absolute: "C:/Development/test-storage/"